### ISSUE TITLE
What this project really do?

### ISSUE THREAD

**Issue by tn1997tn** [MhadhbiXissam/pythonicLua#5]
From the description it's a translator from Python to Lua. But everything started to be confused when I found .pylua extension. What does it mean? Python mixed with Lua? On the Python code on example, I found `ilua`. It's used to evaluate Lua code from Python. It seems this project is not simply a translator from Python to Lua. What this project really do?

**Comment by MhadhbiXissam** [comment]
Hi , I present here how to use the code  : 
- install the project using the cammand : cd $HOME ; git clone "https://github.com/MhadhbiXissam/pythonicLua.git" ; cp $HOME/pythonicLua/pythonicLua/PythonicLua.sublime-syntax $HOME/.config/sublime-text/Packages/User/ ; cp $HOME/pythonicLua/pythonicLua/pythonicLua.sublime-build $HOME/.config/sublime-text/Packages/User/ 
- sure this assume you are linux user , me mint , and used with sublime text .
- create a file named example.lua.pylua ( because the compiler is going to generate file with same name as this file but by removing the (.pylua) from name .
- open file with sublime 
- sublime will highlight the synthaxe with pylua synthaxe hilighter since is installed through the cammand above .
- copy the python code showed in the example readme page , then select build system from sublime menu the pythonicLua , then press crtl + B (build ) you will see generated code and file generated .
- please refer to the code example to get all available feature from python are able to be translated .
- i welcome by any question .
- this code i used with defold game engine and it worked very well , do not underestimate it
